services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: trump
      POSTGRES_PASSWORD: trump
      POSTGRES_DB: trumpbot
    ports: ["127.0.0.1:5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
