[project]
name = "new-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apscheduler>=3.11.0",
    "psycopg>=3.2.9",
    "psycopg-pool>=3.2.6",
    "pytelegrambotapi>=4.28.0",
    "python-dotenv>=1.1.1",
]
